services:
#    wcs_coav.example:
#        class: WCS\CoavBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
    app.admin.terrain:
        class: WCS\CoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terrain", label: "Terrain" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Terrain
            - ~


    app.admin.flight:
        class: WCS\CoavBundle\Admin\FlightAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Flight", label: "Flight" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Flight
            - ~


    app.admin.planemodel:
        class: WCS\CoavBundle\Admin\PlaneModelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "PlaneModel", label: "PlaneModel" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\PlaneModel
            - ~


    app.admin.user:
        class: WCS\CoavBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\User
            - ~


    app.admin.reservation:
        class: WCS\CoavBundle\Admin\ReservationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Reservation", label: "Reservation" }
        arguments:
            - ~
            - WCS\CoavBundle\Entity\Reservation
            - ~